[pytest]
asyncio_mode = auto
markers =
    integration: mark test as requiring Docker and PostgreSQL
filterwarnings =
    ignore::DeprecationWarning
log_cli = true
log_cli_level = INFO

pythonpath = tests